services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "8000:8000"
    networks:
      - app_network
      - db_network  

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: web_container
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app_network
    environment:
      - API_URL=${API_URL} 

networks:
  app_network:
    driver: bridge
  db_network:  
    external: true